media:
  input: src/media
  output: /media
content:
  - name: pages
    label: Pages
    type: collection
    path: src/blog
    fields:
      - name: title
        type: string
      - name: body
        type: rich-text